name: Build and Deploy to ECR

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract ECR repository URI
      id: ecr
      run: echo "::set-output name=uri::$(aws ecr describe-repositories --repository-names coca-cola-lambda --query 'repositories[0].repositoryUri' --output text)"
      
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.ecr.outputs.uri }}
        IMAGE_TAG: dev
      run: |
        docker build -t $ECR_REGISTRY:$IMAGE_TAG .
        docker push $ECR_REGISTRY:$IMAGE_TAG

    - name: Update Lambda function
      env:
        FUNCTION_NAME: coca-cola-lambda
        REGION: us-east-1
        ECR_URI: ${{ steps.ecr.outputs.uri }}
        IMAGE_TAG: dev
      run: |
        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --image-uri $ECR_URI:$IMAGE_TAG \
          --region $REGION
